plugins {
    id "com.android.application"
}

android {
    namespace "com.btgo.mobile"
    compileSdk 36

    defaultConfig {
        applicationId "com.btgo.mobile"
        minSdk 26
        targetSdk 36
        versionCode Integer.parseInt(System.getenv("BT_GO_VERSION_CODE") ?: "8")
        versionName System.getenv("BT_GO_VERSION_NAME") ?: "0.1.8"
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.aar"])
}
